### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bjorntirsensbab** [dolanmiu/vite-plugin-scope-tailwind#1]
I'm getting this error when trying to start the dev server in my React-TS app:

(node:45639) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
failed to load config from /Users/btir/projects/digital-sales/savings-calculator-app/vite.config.ts
error when starting dev server:
/Users/btir/projects/digital-sales/savings-calculator-app/node_modules/vite-plugin-scope-tailwind/dist/es/index.js:1
import p from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

This is part of my package.json

"dependencies": {
    "@headlessui/react": "^1.7.15",
    "@sbab-ui/components": "^0.21.0",
    "@sbab-ui/drafts": "^0.16.0",
    "@sbab-ui/icons": "^2.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-number-format": "^5.1.4"
  },
  "devDependencies": {
    "@homebuyers/styles": "^0.1.2",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^14.0.0",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.1.0",
    "@typescript-eslint/parser": "^6.1.0",
    "@vitejs/plugin-react": "^4.0.3",
    "@vitest/coverage-v8": "^0.33.0",
    "autoprefixer": "^10.4.14",
    "cypress": "^12.17.2",
    "cypress-vite": "^1.4.2",
    "eslint": "^8.45.0",
    "eslint-plugin-cypress": "^2.13.3",
    "eslint-plugin-html": "^7.1.0",
    "eslint-plugin-react": "^7.33.0",
    "jsdom": "^22.1.0",
    "postcss": "^8.4.27",
    "prettier-plugin-tailwindcss": "^0.4.1",
    "resize-observer-polyfill": "^1.5.1",
    "start-server-and-test": "^2.0.0",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.1.6",
    "vite": "^4.4.6",
    "vite-plugin-scope-tailwind": "^1.1.0",
    "vitest": "^0.33.0"
  }

**Comment by dolanmiu** [comment]
Try to set "type": "module" in the package.json as described in the error

**Comment by bjorntirsensbab** [comment]
I already have "type": "module", in my package.json. If i add it to the node_modules/vite-plugin-scope-tailwind/package.json i get this error message: 

failed to load config from /Users/btir/projects/digital-sales/savings-calculator-app/vite.config.ts
error when starting dev server:
ReferenceError: module is not defined in ES module scope
    at file:///Users/btir/projects/digital-sales/savings-calculator-app/node_modules/vite-plugin-scope-tailwind/dist/es/index.js:104:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by maheshbansod** [comment]
Same problem for me.
`"type": "module"` already exists in my package.json.

But if I put `"type": "module"` in `node_modules/vite-plugin-scope-tailwind/package.json`,
I get the error:
```
ReferenceError: module is not defined in ES module scope
    at file:///**/node_modules/vite-plugin-scope-tailwind/dist/es/index.js:110:1
    ....
    <backtrace>
    ...
```
 
It looks like `/dist/es/index.js` contains a `module.exports`

**Comment by dolanmiu** [comment]
As it should no? ESM is `module.exports`

**Comment by maheshbansod** [comment]
@dolanmiu No, that's CJS i think.
ESM is just `export xx`

**Comment by dolanmiu** [comment]
> Same problem for me. `"type": "module"` already exists in my package.json.
> 
> But if I put `"type": "module"` in `node_modules/vite-plugin-scope-tailwind/package.json`, I get the error:
> 
> ```
> ReferenceError: module is not defined in ES module scope
>     at file:///**/node_modules/vite-plugin-scope-tailwind/dist/es/index.js:110:1
>     ....
>     <backtrace>
>     ...
> ```
> 
> It looks like `/dist/es/index.js` contains a `module.exports`

Thanks for all this invesgiation people, I appreciate it

So the `module.exports` is because I added it for some reason. Maybe it was erroneous. Anyway, its removed:

https://github.com/dolanmiu/vite-plugin-scope-tailwind/commit/10f4a2fd9ffc5bb2a9cc3d593cb5f8d08ca01c12

I have exported the bundles in a better way now in `package.json` so it can find `cjs` and `es` better. 

Hopefully that fixes the issue at `v1.1.1`

**Comment by doneumark** [comment]
@dolanmiu I have `v1.1.1`, and I still get the same error:
```
yarn dev
yarn run v1.22.19
$ vite
(node:6376) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
failed to load config from /.../vite.config.ts
error when starting dev server:
/.../node_modules/vite-plugin-scope-tailwind/dist/es/index.js:1
import p from "path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
error Command failed with exit code 1.
```

**Comment by dolanmiu** [comment]
@doneumark can you share with me your vite config, tsconfig and package.json?

**Comment by Tosheen** [comment]
I am experiencing the same issue.

Here is the minimal repo: https://github.com/Tosheen/tailwind-vite-starter

![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/12643248/84ee238e-5ca5-4549-9990-9a73c8eaa285)

**Comment by Tosheen** [comment]
Any updates on this?

The plugin seems like a god sent.

**Comment by dolanmiu** [comment]
> Any updates on this?
> 
> The plugin seems like a god sent.

It really is! We use it at work, and it's brilliant

**Comment by dolanmiu** [comment]
> I am experiencing the same issue.
> 
> Here is the minimal repo: https://github.com/Tosheen/tailwind-vite-starter
> 
> ![image](https://user-images.githubusercontent.com/12643248/266367990-84ee238e-5ca5-4549-9990-9a73c8eaa285.png)

All fixed!

Thank you @Tosheen for the reproduction steps. All fixed in `1.1.2`

It was to do with the file extensions. Seems like adding `mjs` and `cjs` to the dist files did the trick. Previously, I only had `.js` file extensions.

This was how `@vitejs/plugin-react` did it:

![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/2917613/48e29ece-1cb2-4468-aba5-59221ad0c651)

So I did something similar:

![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/2917613/952a5d62-96b6-4381-a3ad-a4249c7bd2fe)

**Comment by Tosheen** [comment]
I tried installing the latest version but for some reason tailwind classes are no longer working. Also hashed class seems to have no properties attached.

![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/12643248/de6fa43b-3d74-4946-9b4e-37fa9f1867b4)

**Comment by dolanmiu** [comment]
@Tosheen Odd... I will look at this when I come home from work, thanks for your patience

**Comment by Tosheen** [comment]
No worries, Thank you.

**Comment by dolanmiu** [comment]
Figured out the issue, it is because `require` doesn't exist in `ESM`:

```
ReferenceError: require is not defined
```

Here, it tries to get the current postcss config, it works well in CommonJS though:

https://github.com/dolanmiu/vite-plugin-scope-tailwind/blob/master/src/get-postcss-config.ts#L5

Trying to figure out a way to do this so it works for both CommonJS and ESM

Any ideas would be appreciated

**Comment by dolanmiu** [comment]
@Tosheen can you try `1.1.3`?

I managed to get it working on your example

![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/2917613/fb7d85e3-df75-4975-9399-8f33956723f1)

**Comment by Tosheen** [comment]
Of course.
Has 1.1.3 been released? :)

**Comment by dolanmiu** [comment]
It has yes:

https://www.npmjs.com/package/vite-plugin-scope-tailwind

**Comment by Tosheen** [comment]
oh let me try. Github still says 1.1.2.

**Comment by Tosheen** [comment]
It works, well done.

I will have to test how this works with our internal component library and will get back to you.

Thanks

**Comment by dolanmiu** [comment]
Glad it's all working! Yes, keep me updated

**Comment by Tosheen** [comment]
I am having issues with a storybook. It reports this kind of error:
![image](https://github.com/dolanmiu/vite-plugin-scope-tailwind/assets/12643248/899d37b2-198a-4d7a-bb92-3d69dd486aac)

It seems that vite config gets picked up by the storybook but it crashes

**Comment by Tosheen** [comment]
Are you guys using storybook with this plugin as well?

I am having issues to make storybook work. My repo is updated to see what I mean.
Meanwhile I will work on the solution as well. Its quite important to have storybook while developing a component library.

**Comment by dolanmiu** [comment]
can you provide some reproduction steps?

We use it with storybook too just fine

**Comment by Tosheen** [comment]
I have updated the repo to use storybook, there is one story component. However when storybook is initiated error messages gets thrown out.

https://github.com/Tosheen/tailwind-vite-starter

**Comment by jkohlin** [comment]
I'm on 1.1.6 and I get this error:
```bash 
error when starting dev server:
Error: Cannot find module '...\node_modules\autoprefixer'
Require stack:
- ...\node_modules\vite-plugin-scope-tailwind\dist\cjs\index.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ...\node_modules\vite-plugin-scope-tailwind\dist\cjs\index.cjs:1:2901       
    at Array.map (<anonymous>)
    at config (...\node_modules\vite-plugin-scope-tailwind\dist\cjs\index.cjs:1:2894)
    at runConfigHook (file:...dist/node/chunks/dep-1d3a4915.js:66116:31)
    at async resolveConfig (file:...dist/node/chunks/dep-1d3a4915.js:65568:14)
    at async _createServer (file:...dist/node/chunks/dep-1d3a4915.js:64805:20)
```
...but I solved it by installing autoprefixer as a dev dependency. Shouldn't that been handled when installing your package? 
like in here?
```json
        "vite-plugin-scope-tailwind": {
            "version": "1.1.6",
            "dev": true,
           ⬇️
            "requires": {
                "@types/uniqid": "^5.3.2",
                "app-root-path": "^3.1.0",
                "uniqid": "^5.4.0"
            }
        },

```
